// <auto-generated />
namespace PSAWebAPI.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class SubDModelUpdatedStartAndCompDateTime : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SubDModelUpdatedStartAndCompDateTime));
        
        string IMigrationMetadata.Id
        {
            get { return "201811092314006_SubDModelUpdatedStartAndCompDateTime"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
